[workspace]
members = [
    'example',
    'adder',
    'add_one',
    'restaurant',
    'minigrep',
    'gui',
    'blog',
    'diff-wasm'
]

[workspace.package]
authors = ["luoxinzheng <luoxinzheng@fagougou.com>"]
version = "0.1.0"
edition = "2021"
