[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
diff = "0.1.13"
liff = "0.1.1"
levenshtein-diff = "0.2.4"
similar="2.2.1"
unicode-segmentation = "1.10.1"
